name: Run Nix Checks

on:
  pull_request:
    branches: [main]

jobs:
  checks:
    name: Run all checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v2026-02-22

      - name: Run all checks
        run: nix flake check --print-build-logs
